template: Hola, %s!!

defaultName: Amigo

fooConfig:
    url: somedb.somedomain.com
    threshold: 3.345

dataSourceName: "Sample Service Jdbc DataSource ( MariaDb )"

dataSourceFactory:
  # the name of your JDBC driver
  driverClass: org.mariadb.jdbc.Driver
  # the username
  user: sample
  # the password
  password: insecure
  # the JDBC URL
  url: jdbc:mysql://localhost:3306/sampleservice_test
  # any properties specific to your JDBC driver
  properties:
    charSet: UTF-8
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s
  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

swaggerSetup:
  endpointOverride: "localhost"
  #endpointOverride: "localhost:80"

apiInfoData:
  apiVersion: 1.0.0
  title: "Servizio API Server Demo"
  description: "Demo of Servizio - a bundled and bootstrapped Java application and REST API server framework foundation ( based on DropWizard )"
  termsOfServiceUrl: "None"
  contact: "sndshd@gmail.com"
  license: "CC0 1.0 Universal"
  licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/"

server:
  requestLog:
    timeZone: UTC
    appenders:
     - type: file
       currentLogFilename: var/output/logs/access.log 
       threshold: ALL
       archive: true
       archivedLogFilenamePattern: var/output/logs/access.%d{yyyy-MM-dd-HH}.log 
       archivedFileCount: 24
       timeZone: UTC

requestTracing:
    requestIdContext: "servizio"
    enableLogging: false

metrics:
  reporters:
    - type: log
      frequency: 10 seconds
      logger: "com.fooorg.fooproj.metrics"
      durationUnit: milliseconds
      rateUnit: seconds
